### ISSUE TITLE
Solutions exercises

### ISSUE THREAD

**Issue by turutupa** [haskell-beginners-2022/exercises#45]
Hi @chshersh! After each week, could you provide the solutions to the exercises of the prev week? Or if the solutions are already available could you let me know where I can find them? thx in advance!

**Comment by chshersh** [comment]
@turutupa Hi! 👋🏻 
Yep, I was planning to provide solutions for chapters. Will create solutions for Lecture 1 some time this week 👍🏻

**Comment by turutupa** [comment]
That'd be great @chshersh !! Thank you very much
