### ISSUE TITLE
Add comments on where to add imports

### ISSUE THREAD

**Issue by bulters** [haskell-beginners-2022/exercises#52]
Turns out that DocTest is not handling imports after "certain statements" (e.g. the line containing `$setup` in Lecture3.hs) very well. Add some comments in all of the `LectureN.hs` files on where to "potentially" add imports.

n.b. I will pick this up, this serves mainly as a reminder.

**Comment by bulters** [comment]
@chshersh you can assign this issue to me if you want ;-)

**Comment by chshersh** [comment]
@bulters Done 🙂

**Comment by chshersh** [comment]
Closed by #53
