### ISSUE TITLE
Use 'hedgehog-classes' from Hackage

### ISSUE THREAD

**Issue by chshersh** [haskell-beginners-2022/exercises#79]
I'm using the [`hedgehog-classes`](https://hackage.haskell.org/package/hedgehog-classes) package from my fork with the required fixes:

https://github.com/haskell-beginners-2022/exercises/blob/222640bde98634e06a9a89a61456fc0a5aaf6ea5/cabal.project#L5-L8

However, a new version was released to Hackage recently. I hope it includes my fix. In that case, we could switch to using the library from Hackage.

**Comment by jakalx** [comment]
I just checked with the most recent version on hackage (0.2.5.3) but that release does not include your fixes :(

**Comment by chshersh** [comment]
That's too bad 😞 
I checked the contents of the library on Hackage and it indeed doesn't contain the fixes.

I've created an issue to ask about a Hackage release:

* https://github.com/hedgehogqa/haskell-hedgehog-classes/issues/46

**Comment by chshersh** [comment]
Fixed in #88
